### ISSUE TITLE
write py program to generate random number from 0 to 9

### ISSUE THREAD

**Issue by GhadgeGauri** [GhadgeGauri/HactoberFest23#2]

**Comment by gauriiighadge** [comment]
Please assign me this task

**Comment by nexuspy** [comment]
can I work On this?

**Comment by Harsha19-08** [comment]
can u please assign me this

**Comment by Harsha19-08** [comment]
is this got executed according to ur issue

**Comment by Sankalp20Tiwari** [comment]
Hey, I would like to work on this issue . So, I request you to please assign this issue to me .
